included:

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  
disabled_rules:
  - trailing_whitespace  
  
line_length: 180
force_unwrapping: error
variable_name:
  max_length:
    warning: 40
    error: 50
  min_length:
    error: 1
  excluded:
    - row
    - key
    - id
    - url
    - uri
    - URI
    - URL
colon: error